In [1]:
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [11]:
df=pd.read_csv("../resources/Excel_sheets/hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [12]:
df.experience.fillna('zero',inplace=True)

In [13]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [14]:
from word2number import w2n

In [15]:
df.experience=df.experience.apply(w2n.word_to_num)

In [16]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [19]:
df.isnull().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [23]:
df[df.isnull().any(axis=1)]

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
6          10                    NaN                           7      72000

In [30]:
df[df.iloc[:,:]==np.NaN]

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    NaN                         NaN        NaN
1         NaN                    NaN                         NaN        NaN
2         NaN                    NaN                         NaN        NaN
3         NaN                    NaN                         NaN        NaN
4         NaN                    NaN                         NaN        NaN
5         NaN                    NaN                         NaN        NaN
6         NaN                    NaN                         NaN        NaN
7         NaN                    NaN                         NaN        NaN

In [32]:
df.loc[df.isnull().any(axis=1)]

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
6          10                    NaN                           7      72000

In [34]:
df.isnull().any(axis=0)

experience                    False
test_score(out of 10)          True
interview_score(out of 10)    False
salary($)                     False
dtype: bool

In [36]:
med=df['test_score(out of 10)'].median()
med

8.0

In [37]:
df['test_score(out of 10)'].fillna(med,inplace=True)

In [49]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

## model

In [42]:
X=df[["experience",'test_score(out of 10)',"interview_score(out of 10)"]]
y=df["salary($)"]

In [44]:
reg=LinearRegression()
model=reg.fit(X,y)

In [45]:
model.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [46]:
model.intercept_

17737.26346433768

In [48]:
model.predict([[2,9,6]])

array([53205.96797671])

In [50]:
model.predict([[12,10,10]])

array([92002.18340611])