In [26]:
from math import log

def pattern(width,row,start):
    n=2*width
    shift=n
    for r in range(n):
        if start<=r<=log(n,2):
            shift=shift/2
            for i in range(n):
                print(2*i,end="")
                if not (2*i)//shift:
                    #print("here",shift)
                    print("*$",end="")
                else:
                    print("$$",end="")
            print('\n')
            

pattern(5,4,1)

0*$2*$4*$6$$8$$

0*$2*$4$$6$$8$$

0*$2$$4$$6$$8$$



In [4]:
import numpy as np

In [5]:
def cuboid(center,length):
    x,y,z=center
    vertex_list=[]
    l1,l2,l3=length
    l1=l1//2
    l2=l2//2
    l3=l3//2

    for i in (-l1,l1):
        for j in (-l2,l2):
            for k in (-l3,l3):
                vertex_list.append((x+i,y+j,z+k))

    edge_list=((0,2),(2,3),(3,7),(5,7),(1,5),(1,3),(2,6),(6,7),(4,6),(4,5),(0,4),(0,1))
    return vertex_list,edge_list

In [13]:
arr=np.array(cuboid((0,0,400),(500,500,500))[0],dtype=np.int16)
arr

array([[-250, -250,  150],
       [-250, -250,  650],
       [-250,  250,  150],
       [-250,  250,  650],
       [ 250, -250,  150],
       [ 250, -250,  650],
       [ 250,  250,  150],
       [ 250,  250,  650]], dtype=int16)

In [7]:
np.mean(arr,axis=0)

array([  0.,   0., 400.])

In [8]:
a = np.array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
np.mean(a,axis=0)

array([10.        , 11.33333333, 14.66666667])

In [16]:
theta=60
tfm=np.array([[np.cos(theta),np.sin(theta)],[-np.sin(theta),np.cos(theta)]])
np.dot(arr[:,1:],tfm).astype(np.int16,copy=False).tolist()

[[283, -66],
 [436, -542],
 [-192, -219],
 [-39, -695],
 [283, -66],
 [436, -542],
 [-192, -219],
 [-39, -695]]